version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    image: php:fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - code-network

  socket:
    build: .
    command: php ./php-socket.php
    ports:
      - '8090:8090'
    volumes:
      - ./src:/var/www/html
    networks:
      - code-network

networks:
  code-network:
    driver: bridge
